### ISSUE TITLE
decrease time between upgrade checks

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/custom-image#20]
Currently we check for an upgrade once per day:

https://github.com/Vanilla-OS/custom-image/blob/45daf9deec4940fa172a13540cfe9c02df9c1e89/.github/workflows/vib-build.yml#L9

This is really conservative. An upgrade check takes only a couple of seconds and two api calls. 

I think we can reduce it to every 4 or 6 hours.
Still shouldn't put much strain on the registry and means that users don't get updates possibly 24 hours dalyed.

**Comment by kbdharun** [comment]
I think 6 hours would work the best. (Meaning 4 requests per day)

**Comment by taukakao** [comment]
Fixed by 73b22ce6bdb92ffa2966676b9e85b80686dee963
