### ISSUE TITLE
Recipe not working with vib

### ISSUE THREAD

**Issue by rommeswi** [Vanilla-OS/custom-image#24]
I'm not sure if this repo or the vib repo is the right place to post this issue.

When trying to use recipe.yml with a local vib installation, vib complains it cannot find a plugin file 'usr//...' with a misspelling of the path due to double '/'.

If this is intentional, the readme should say that the recipe cannot/should not be built with vib directly.

**Comment by axtloss** [comment]
This is neither a vib nor a core image issue, you haven't installed vib properly and are missing plugins (the plugin.tar.xz from the vib releases page)
the path is not misspelled, double slashes are perfectly fine

**Comment by rommeswi** [comment]
I simply followed the instructions at https://docs.vanillaos.org/vib/en/getting-started for installing vib.
If these instructions are insufficient, then it is a documentation issue.

**Comment by kbdharun** [comment]
> I simply followed the instructions at https://docs.vanillaos.org/vib/en/getting-started for installing vib. If these instructions are insufficient, then it is a documentation issue.

The documentation has been updated in the source at https://github.com/Vanilla-OS/Vib/blob/main/docs/articles/en/getting-started.md two weeks ago, the online version in production is generally resynced periodically once every few weeks (when we make some updates) so it will be reflected soon.

If you are using recent versions of Vib, I would suggest checking the release notes to stay updated before the docs are updated.

**Comment by rommeswi** [comment]
Since following the 'getting started' tutorial entails using the latest version of vib, I would recommend adding the sentence to the getting started tutorial: "If you are using recent versions of Vib, I would suggest checking the release notes to stay updated before the docs are updated."
