### ISSUE TITLE
Make plugin does not substitute buildCommand

### ISSUE THREAD

**Issue by rommeswi** [Vanilla-OS/custom-image#27]
In my repo, I have a file https://github.com/rommeswi/vib-image/blob/main/modules/gnome/totp-extension.yml
with a module that is supposed to use a git source and use make to build a gnome extension.

```name: gnome-shell-extension-totp
type: make
buildCommand: "echo TOTP-extension-installation"
installCommand: "make install -d"
source:
  type: git
  url: https://github.com/dkosmari/gnome-shell-extension-totp
  branch: master
  commit: latest
modules:
  - name: build-deps
    type: apt
    source:
      packages:
      - jq
      - make
      - git
```

Unfortunately, the make plugin never substitutes the buildCommand and installCommand and tries to execute `make && make install`. I tried all variations of spelling, buildcommand, BuildCommand, buildCommand and tried to put the string into " " or not. Vib does not complain, it simply never substitutes.

I looked into the code of the plugin and found that it is quite messy when it comes to capitalization. The json has everything in lowercase. The go struct uses twice uppercase and the manual states one should use installCommand. So there may be a problem upstream. I could not find a make module being used in the core image or desktop image to verify.

Another issue I find strange but this may be intended: without adding a submodule that installs make, the make plugin does not even get to the stage where the command is executed. Given that it is strange to use make without having make installed, it would perhaps make sense to auto-include it?

**Comment by axtloss** [comment]
These definitions for the make plugin aren't released 
the current release for the make plugin is here https://github.com/Vanilla-OS/Vib/blob/v0.8.1/plugins/make.go

**Comment by rommeswi** [comment]
So that means that the possibility of supplying a different make command has simply been removed? Why? Surely not every make project is build the same way...

**Comment by axtloss** [comment]
what? no, it's something that was added but hasn't been released yet
