### ISSUE TITLE
attestation fails if base image is not owned by Vanilla-OS

### ISSUE THREAD

**Issue by rommeswi** [Vanilla-OS/custom-image#28]
I think it would be useful to have a field for the image owner in the recipe.yml

If the image owner is not Vanilla-OS, one currently has to edit the build.yml file as well (directly in the code)

Perhaps the most user friendly would be to have separate fields such as:
image:
  type: ghcr
  owner: Vanilla-OS
  name: desktop
  branch: main

The owner should by default then be used for the attestation and stages: base should be automatically generated from the above data.

**Comment by rommeswi** [comment]
The attestation also displays:

```Run gh attestation verify oci://ghcr.io/ghcr.io/..../desktop:... ....```

which initially got me confused to think that to get the attestation working I had to remove ghcr.io from the image url.

**Comment by taukakao** [comment]
Attestation is not part of vib so it shouldn't be inside the vib recipe in my opinion.

To be honest, I don't think it should be here at all. I will discuss this with the team and then get back to you.

**Comment by axtloss** [comment]
Yeah this wouldn't work unless we add attestation support to vib, which is too platform specific and not happening.

**Comment by axtloss** [comment]
also this doesn't seem like a bug to me
if the base image isn't a vanilla image then isn't attestation supposed to fail when specifying the owner as vanilla os

**Comment by taukakao** [comment]
Bug or not, it's still bad UX.
